/**
 * Tributech DataSpace Twin API
 * API for managing twin instances.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

import { ProblemDetails } from '../model/models';
import { TwinGraph } from '../model/models';
import { TwinGraphQuery } from '../model/models';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { TwinApiConfiguration }                                     from '../configuration';



@Injectable({
  providedIn: 'root'
})
export class QueryService {

    protected basePath = 'http://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new TwinApiConfiguration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: TwinApiConfiguration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }


    private addToHttpParams(httpParams: HttpParams, value: any, key?: string): HttpParams {
        if (typeof value === "object" && value instanceof Date === false) {
            httpParams = this.addToHttpParamsRecursive(httpParams, value);
        } else {
            httpParams = this.addToHttpParamsRecursive(httpParams, value, key);
        }
        return httpParams;
    }

    private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
        if (value == null) {
            return httpParams;
        }

        if (typeof value === "object") {
            if (Array.isArray(value)) {
                (value as any[]).forEach( elem => httpParams = this.addToHttpParamsRecursive(httpParams, elem, key));
            } else if (value instanceof Date) {
                if (key != null) {
                    httpParams = httpParams.append(key,
                        (value as Date).toISOString().substr(0, 10));
                } else {
                   throw Error("key may not be null if value is Date");
                }
            } else {
                Object.keys(value).forEach( k => httpParams = this.addToHttpParamsRecursive(
                    httpParams, value[k], key != null ? `${key}.${k}` : k));
            }
        } else if (key != null) {
            httpParams = httpParams.append(key, value);
        } else {
            throw Error("key may not be null if value is not object or array");
        }
        return httpParams;
    }

    /**
     * Query digital twin graph using cypher query.
     * @param match Cypher query &lt;a href&#x3D;\&quot;https://neo4j.com/docs/cypher-manual/current/clauses/match/\&quot; target&#x3D;\&quot;_blank\&quot;&gt;MATCH&lt;/a&gt; part.  e.g. \&quot;(twin:Twin)\&quot;, \&quot;(stream:Twin:BaseStreamTributechIoV1)\&quot;, \&quot;(stream:Twin:BaseStreamTributechIoV1)-[relationship:Options]-&gt;(option:Twin:BaseOptionsTributechIoV1)\&quot;,...
     * @param _with Cypher query &lt;a href&#x3D;\&quot;https://neo4j.com/docs/cypher-manual/current/clauses/with/\&quot; target&#x3D;\&quot;_blank\&quot;&gt;WITH&lt;/a&gt; part.  The result must be projected to lists named \&quot;nodes\&quot; and \&quot;relationships\&quot; to be returned which can be done at the WITH part.  To return an empty list for one of them you can use \&quot;[] AS relationships\&quot;.  e.g. \&quot;stream AS nodes, [] AS relationships\&quot;, \&quot;collect(distinct stream) + collect(distinct option) AS nodes, collect(relationship) AS relationships\&quot;),...
     * @param where (Optional) Cypher query &lt;a href&#x3D;\&quot;https://neo4j.com/docs/cypher-manual/current/clauses/where/\&quot; target&#x3D;\&quot;_blank\&quot;&gt;WHERE&lt;/a&gt; part.  e.g. \&quot;stream.ValueMetadataId &#x3D; \&#39;6e02502-bfc5-4182-aa3b-891965020e14\&#39;\&quot;, \&quot;stream.MerkleTreeDepth IS NOT NULL\&quot;, \&quot;option:PersistenceOptionsTributechIoV1\&quot;,...
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getTwinGraphByCypherQuery(match: string, _with: string, where?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json'}): Observable<TwinGraph>;
    public getTwinGraphByCypherQuery(match: string, _with: string, where?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json'}): Observable<HttpResponse<TwinGraph>>;
    public getTwinGraphByCypherQuery(match: string, _with: string, where?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json'}): Observable<HttpEvent<TwinGraph>>;
    public getTwinGraphByCypherQuery(match: string, _with: string, where?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json'}): Observable<any> {
        if (match === null || match === undefined) {
            throw new Error('Required parameter match was null or undefined when calling getTwinGraphByCypherQuery.');
        }
        if (_with === null || _with === undefined) {
            throw new Error('Required parameter _with was null or undefined when calling getTwinGraphByCypherQuery.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (match !== undefined && match !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>match, 'Match');
        }
        if (where !== undefined && where !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>where, 'Where');
        }
        if (_with !== undefined && _with !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>_with, 'With');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (OAuth2) required
        credential = this.configuration.lookupCredential('OAuth2');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'text/plain',
                'application/json',
                'text/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.post<TwinGraph>(`${this.configuration.basePath}/query/cypher`,
            null,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Query digital twin graph by criterias.
     * @param twinGraphQuery The graph query
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getTwinGraphByQuery(twinGraphQuery?: TwinGraphQuery, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json'}): Observable<TwinGraph>;
    public getTwinGraphByQuery(twinGraphQuery?: TwinGraphQuery, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json'}): Observable<HttpResponse<TwinGraph>>;
    public getTwinGraphByQuery(twinGraphQuery?: TwinGraphQuery, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json'}): Observable<HttpEvent<TwinGraph>>;
    public getTwinGraphByQuery(twinGraphQuery?: TwinGraphQuery, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json'}): Observable<any> {

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (OAuth2) required
        credential = this.configuration.lookupCredential('OAuth2');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'text/plain',
                'application/json',
                'text/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.post<TwinGraph>(`${this.configuration.basePath}/query/subgraph`,
            twinGraphQuery,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
