/**
 * Tributech DataSpace Twin API
 * API for managing twin instances.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DigitalTwin } from './digital-twin';
import { Relationship } from './relationship';


export interface TwinGraph { 
    digitalTwins?: Array<DigitalTwin> | null;
    relationships?: Array<Relationship> | null;
}

