/**
 * Tributech DataSpace Twin API
 * API for managing twin instances.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ValidationProblemDetails { 
  [key: string]: any | any;


    errors?: { [key: string]: Array<string>; } | null;
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
}

